/**
 * Auth: password hashing/verification, session cookie issuance and verification.
 *
 * Password hashing: PBKDF2-SHA256, 100000 iterations, 16-byte random salt,
 * 256-bit (32-byte) derived key, salt and hash both standard base64 (RFC 4648,
 * with padding). Mirrors scripts/user-add.mjs exactly — both use the same
 * standard Web Crypto PBKDF2 algorithm, so hashes generated by the script are
 * accepted here without modification.
 *
 * Session cookie `sp_session`:
 *   base64url(username) + "." + expiryEpochMs + "." + hex(HMAC-SHA256(secret, username + "." + expiryEpochMs))
 * Attributes: HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=7776000 (90 days).
 */

import { users, type Role } from './users';

const PBKDF2_ITERATIONS = 100_000;
const DERIVED_KEY_BITS = 256;
const SESSION_MAX_AGE_SECONDS = 7_776_000; // 90 days
const SESSION_MAX_AGE_MS = SESSION_MAX_AGE_SECONDS * 1000;
const SESSION_COOKIE_NAME = 'sp_session';

// Fixed dummy salt/hash used only to equalize PBKDF2 work for unknown usernames
// at login, so response time cannot be used to enumerate valid accounts. This
// is not tied to any real account and grants no access on its own — login()
// only ever succeeds when the username is also present in `users`.
const DUMMY_SALT_B64 = '0CLaljPy0RnIxaRonU77IA==';
const DUMMY_HASH_B64 = 'RyF8eegkqh0z7i2+lHjM32IDnwTgbzK/rMHCA6RC50A=';

export interface Session {
  username: string;
  role: Role;
}

/* ------------------------------------------------------------------ encoding helpers */

function bytesToBase64(bytes: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

function base64ToBytes(b64: string): Uint8Array<ArrayBuffer> {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function base64UrlToBytes(b64url: string): Uint8Array<ArrayBuffer> {
  let b64 = b64url.replace(/-/g, '+').replace(/_/g, '/');
  while (b64.length % 4 !== 0) b64 += '=';
  return base64ToBytes(b64);
}

function bytesToBase64Url(bytes: Uint8Array): string {
  return bytesToBase64(bytes).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function bytesToHex(bytes: Uint8Array): string {
  let hex = '';
  for (let i = 0; i < bytes.length; i++) hex += bytes[i].toString(16).padStart(2, '0');
  return hex;
}

function hexToBytes(hex: string): Uint8Array<ArrayBuffer> | null {
  if (hex.length % 2 !== 0 || !/^[0-9a-f]*$/i.test(hex)) return null;
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) bytes[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16);
  return bytes;
}

/** Constant-time byte comparison: loop XOR-ing every byte, accumulate, compare once. */
function timingSafeEqual(a: Uint8Array, b: Uint8Array): boolean {
  const len = Math.max(a.length, b.length);
  let diff = a.length ^ b.length;
  for (let i = 0; i < len; i++) {
    const av = i < a.length ? a[i] : 0;
    const bv = i < b.length ? b[i] : 0;
    diff |= av ^ bv;
  }
  return diff === 0;
}

/* ------------------------------------------------------------------ password hashing */

async function pbkdf2(password: string, salt: Uint8Array<ArrayBuffer>): Promise<Uint8Array<ArrayBuffer>> {
  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(password),
    'PBKDF2',
    false,
    ['deriveBits'],
  );
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', hash: 'SHA-256', salt, iterations: PBKDF2_ITERATIONS },
    keyMaterial,
    DERIVED_KEY_BITS,
  );
  return new Uint8Array(bits);
}

/**
 * Verifies a login attempt. Always performs a full PBKDF2 derivation (against
 * a dummy salt when the username is unknown) and a constant-time comparison,
 * so an unknown username takes the same amount of work as a wrong password —
 * it cannot be used to enumerate valid usernames by timing.
 */
export async function verifyLogin(username: string, password: string): Promise<Role | null> {
  const user = users[username];
  const saltB64 = user ? user.salt : DUMMY_SALT_B64;
  const expectedB64 = user ? user.hash : DUMMY_HASH_B64;

  const derived = await pbkdf2(password, base64ToBytes(saltB64));
  const matches = timingSafeEqual(derived, base64ToBytes(expectedB64));

  if (user && matches) return user.role;
  return null;
}

/* ------------------------------------------------------------------ session cookie */

async function hmacHex(secret: string, message: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  );
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(message));
  return bytesToHex(new Uint8Array(sig));
}

function cookieAttributes(maxAgeSeconds: number): string {
  return `HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${maxAgeSeconds}`;
}

/** Builds the `Set-Cookie` header value for a fresh 90-day session. */
export async function createSessionCookie(username: string, secret: string): Promise<string> {
  const expiry = Date.now() + SESSION_MAX_AGE_MS;
  const mac = await hmacHex(secret, `${username}.${expiry}`);
  const value = `${bytesToBase64Url(new TextEncoder().encode(username))}.${expiry}.${mac}`;
  return `${SESSION_COOKIE_NAME}=${value}; ${cookieAttributes(SESSION_MAX_AGE_SECONDS)}`;
}

/** Builds the `Set-Cookie` header value that deletes the session cookie. */
export function clearSessionCookie(): string {
  return `${SESSION_COOKIE_NAME}=; ${cookieAttributes(0)}`;
}

function readCookie(cookieHeader: string | null, name: string): string | null {
  if (!cookieHeader) return null;
  for (const part of cookieHeader.split(';')) {
    const eq = part.indexOf('=');
    if (eq === -1) continue;
    if (part.slice(0, eq).trim() === name) return part.slice(eq + 1).trim();
  }
  return null;
}

/**
 * Verifies the session cookie: HMAC (constant-time), expiry, and that the
 * username still exists in `users`. Returns null on any failure — callers
 * must treat null as 401 and clear the cookie.
 */
export async function verifySession(cookieHeader: string | null, secret: string): Promise<Session | null> {
  const raw = readCookie(cookieHeader, SESSION_COOKIE_NAME);
  if (!raw) return null;

  const parts = raw.split('.');
  if (parts.length !== 3) return null;
  const [usernameB64Url, expiryStr, mac] = parts;

  if (!/^\d{1,20}$/.test(expiryStr)) return null;

  let username: string;
  try {
    username = new TextDecoder().decode(base64UrlToBytes(usernameB64Url));
  } catch {
    return null;
  }

  const expectedMac = await hmacHex(secret, `${username}.${expiryStr}`);
  const macBytes = hexToBytes(mac);
  const expectedMacBytes = hexToBytes(expectedMac);
  if (!macBytes || !expectedMacBytes || !timingSafeEqual(macBytes, expectedMacBytes)) return null;

  if (Date.now() > Number(expiryStr)) return null;

  const user = users[username];
  if (!user) return null;

  return { username, role: user.role };
}
